# #44: Menata ulang penempatan kolom pada Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  3  7  7  3  9
1  2  9  5  8  7
2  8  9  4  5  1
3  2  7  3  1  6
4  7  1  4  7  4

## Menata ulang penempatan kolom pada Data Frame

In [3]:
df[['D', 'C', 'A', 'E', 'B']]

   D  C  A  E  B
0  3  7  3  9  7
1  8  5  2  7  9
2  5  4  8  1  9
3  1  3  2  6  7
4  7  4  7  4  1

In [4]:
df

   A  B  C  D  E
0  3  7  7  3  9
1  2  9  5  8  7
2  8  9  4  5  1
3  2  7  3  1  6
4  7  1  4  7  4

In [5]:
df = df[['D', 'C', 'A', 'E', 'B']]
df

   D  C  A  E  B
0  3  7  3  9  7
1  8  5  2  7  9
2  5  4  8  1  9
3  1  3  2  6  7
4  7  4  7  4  1