# #18: Membentuk dummy Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Membentuk Data Frame dari Dictionary

In [2]:
pd.DataFrame({'col1':[1, 2, 3, 4], 
              'col2':[5, 6, 7, 8]})

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

## Membentuk Data Frame dari Numpy Array

In [3]:
n_rows = 5
n_cols = 3

arr = np.random.randint(1, 20, size=(n_rows, n_cols))
arr

array([[15,  4, 10],
       [10, 14,  6],
       [13,  6, 16],
       [ 6, 10,  7],
       [17, 10, 18]])

In [4]:
pd.DataFrame(arr, columns=tuple('ABC'))

    A   B   C
0  15   4  10
1  10  14   6
2  13   6  16
3   6  10   7
4  17  10  18

## Membentuk Data Frame dengan memanfaatkan `pandas.util.testing`

In [5]:
n_rows = 30 
n_cols = 4 
columns = list('ABCD')

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=columns)

print(df.head())

          A         B         C         D
0 -0.044750  0.304171 -1.005263  0.102070
1 -0.133416 -0.080356  1.648879 -0.327942
2  0.255829 -1.293882  0.670782 -1.127432
3  0.654297  0.436539 -2.337735  0.207894
4 -0.682520 -0.155571 -0.863258  2.217835

In [6]:
n_rows = 5 

data = {
    'A': np.random.randn(n_rows),                 
    'B': np.arange(1, n_rows + 1),                
    'C': pd.date_range('2024-01-01', periods=n_rows), 
    'D': ['foo', 'bar', 'baz', 'qux', 'quux']    
}

df = pd.DataFrame(data)

print(df.head())

          A  B          C     D
0 -2.425281  1 2024-01-01   foo
1  0.180889  2 2024-01-02   bar
2 -2.181896  3 2024-01-03   baz
3 -2.108070  4 2024-01-04   qux
4  1.245548  5 2024-01-05  quux

In [7]:
n_rows = 30  
n_cols = 4   
columns = list('ABCD')  

time_index = pd.date_range(start='2024-01-01', periods=n_rows, freq='D')  

df = pd.DataFrame(np.random.randn(n_rows, n_cols), index=time_index, columns=columns)

print(df.head())

                   A         B         C         D
2024-01-01  0.832537  0.819890 -0.805499 -1.918133
2024-01-02  0.805710  0.717087 -0.077531 -0.050424
2024-01-03  0.144106  0.373599  1.345007  1.116164
2024-01-04  2.023148 -0.493091  0.013670  0.379798
2024-01-05  0.757372  0.851368 -0.759750  1.680890

In [8]:
n_rows = 5
n_cols = 4

data = np.random.randn(n_rows, n_cols)

df = pd.DataFrame(data, columns=list('ABCD'))

df.iloc[0, 1] = np.nan
df.iloc[2, 3] = np.nan
df.iloc[4, 0] = np.nan

print(df.head())

          A         B         C         D
0 -1.537992       NaN  0.245115 -1.004124
1  0.001938 -0.375954 -1.041913 -1.179568
2 -0.624599  0.602643  0.707406       NaN
3  0.953671 -1.405230 -1.291972  0.750678
4       NaN -0.286854  1.382460 -0.689393