# #06: Mengganti nama (label) kolom pada Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  1  2  5  2  7
1  2  3  9  7  9
2  1  4  1  6  8
3  2  3  4  8  7
4  9  9  6  6  6

## Mengganti nama (label) untuk sebuah kolom pada Data Frame

In [3]:
df.rename(columns={'C':'Hobi'})

   A  B  Hobi  D  E
0  1  2     5  2  7
1  2  3     9  7  9
2  1  4     1  6  8
3  2  3     4  8  7
4  9  9     6  6  6

## Mengganti nama (label) untuk banyak kolom pada Data Frame

In [4]:
df.rename(columns={'A':'Nama', 'B':'Alamat', 'D':'Kota'})

   Nama  Alamat  C  Kota  E
0     1       2  5     2  7
1     2       3  9     7  9
2     1       4  1     6  8
3     2       3  4     8  7
4     9       9  6     6  6