# #51: Seleksi baris dengan `between()`
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  6  5  5  4  3
1  5  4  3  9  4
2  8  5  5  3  8
3  2  7  5  6  2
4  7  3  4  4  5
5  2  5  2  7  5
6  3  6  9  2  2
7  1  1  9  4  5
8  2  4  5  3  4
9  5  2  8  6  6

## Seleksi baris dengan `between()`

In [3]:
df[df['A'].between(2, 5)]

   A  B  C  D  E
1  5  4  3  9  4
3  2  7  5  6  2
5  2  5  2  7  5
6  3  6  9  2  2
8  2  4  5  3  4
9  5  2  8  6  6

In [4]:
## DEPRICATED ##
# df[df['A'].between(2, 5, inclusive=False)]

In [5]:
df[df['A'].between(2, 5, inclusive='left')]

   A  B  C  D  E
3  2  7  5  6  2
5  2  5  2  7  5
6  3  6  9  2  2
8  2  4  5  3  4

In [6]:
df[df['A'].between(2, 5, inclusive='right')]

   A  B  C  D  E
1  5  4  3  9  4
6  3  6  9  2  2
9  5  2  8  6  6

In [7]:
df[df['A'].between(2, 5, inclusive='both')]

   A  B  C  D  E
1  5  4  3  9  4
3  2  7  5  6  2
5  2  5  2  7  5
6  3  6  9  2  2
8  2  4  5  3  4
9  5  2  8  6  6

In [8]:
df[df['A'].between(2, 5, inclusive='neither')]

   A  B  C  D  E
6  3  6  9  2  2