# #17: Resampling pada data deret waktu (time series data)
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 365 * 24 
n_cols = 2         
cols = ['col1', 'col2'] 

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df.index = pd.date_range(start='2023-01-01', periods=n_rows, freq='H')

df.head()

                     col1  col2
2023-01-01 00:00:00     6    19
2023-01-01 01:00:00    17    10
2023-01-01 02:00:00    17    16
2023-01-01 03:00:00    17     8
2023-01-01 04:00:00     7    19

## Resampling data dengan interval monthly

In [3]:
df.resample('M')['col1'].sum().to_frame()

            col1
2023-01-31  7163
2023-02-28  6845
2023-03-31  7558
2023-04-30  7171
2023-05-31  7585
2023-06-30  7217
2023-07-31  7038
2023-08-31  7522
2023-09-30  7114
2023-10-31  7458
2023-11-30  7140
2023-12-31  7613

## Resampling data dengan interval daily

In [4]:
df.resample('D')['col1'].sum().to_frame()

            col1
2023-01-01   265
2023-01-02   244
2023-01-03   202
2023-01-04   263
2023-01-05   281
...          ...
2023-12-27   216
2023-12-28   246
2023-12-29   280
2023-12-30   265
2023-12-31   267

[365 rows x 1 columns]