# #01: Menyertakan Prefix dan Suffix pada seluruh Kolom Data Frame

## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 5
n_cols = 5
cols = tuple ('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)),
                 columns=cols)
df

   A  B  C  D  E
0  8  1  3  6  4
1  6  8  1  4  1
2  4  5  7  7  4
3  6  4  3  7  1
4  2  1  2  7  5

In [3]:
tuple('ABCDE')

('A', 'B', 'C', 'D', 'E')

## Menyertakan Prefix Kolom

In [4]:
df.add_prefix('kolom_')

   kolom_A  kolom_B  kolom_C  kolom_D  kolom_E
0        8        1        3        6        4
1        6        8        1        4        1
2        4        5        7        7        4
3        6        4        3        7        1
4        2        1        2        7        5

## Menyertakan Suffix Kolom

In [5]:
df.add_suffix('_field')

   A_field  B_field  C_field  D_field  E_field
0        8        1        3        6        4
1        6        8        1        4        1
2        4        5        7        7        4
3        6        4        3        7        1
4        2        1        2        7        5