# #39: Mengacak urutan baris pada DataFrame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 6
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  2  4  2  3  1
1  3  4  1  3  1
2  3  4  1  4  4
3  2  1  3  4  1
4  3  2  3  3  4
5  4  1  2  3  3

## Mengacak urutan baris pada DataFrame

In [3]:
df.sample(frac=1.0, random_state=1)

   A  B  C  D  E
2  3  4  1  4  4
1  3  4  1  3  1
4  3  2  3  3  4
0  2  4  2  3  1
3  2  1  3  4  1
5  4  1  2  3  3

In [4]:
df.sample(frac=1.0, random_state=1).reset_index(drop=True)

   A  B  C  D  E
0  3  4  1  4  4
1  3  4  1  3  1
2  3  2  3  3  4
3  2  4  2  3  1
4  2  1  3  4  1
5  4  1  2  3  3