# #02: Pemilihan baris (rows selection) pada Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  3  4  2  3  4
1  4  2  3  4  4
2  3  2  2  2  3
3  3  3  1  2  2
4  2  1  1  1  1
5  4  3  2  4  4
6  2  1  2  2  4
7  4  3  4  3  4
8  4  3  1  1  3
9  3  4  1  1  4

## Selection dengan operator logika `|`

In [3]:
df[(df['A'] == 1) | (df['A'] == 3)]

   A  B  C  D  E
0  3  4  2  3  4
2  3  2  2  2  3
3  3  3  1  2  2
9  3  4  1  1  4

## Selection dengan fungsi `isin()`

In [4]:
df[df['A'].isin([1, 3])]

   A  B  C  D  E
0  3  4  2  3  4
2  3  2  2  2  3
3  3  3  1  2  2
9  3  4  1  1  4

## Mengenal operator negasi `~`

In [5]:
df[~df['A'].isin([1, 3])]

   A  B  C  D  E
1  4  2  3  4  4
4  2  1  1  1  1
5  4  3  2  4  4
6  2  1  2  2  4
7  4  3  4  3  4
8  4  3  1  1  3