# #03: Konversi tipe data String ke Numerik pada kolom Data Frame
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
data = {'col1':['1', '2', '3', 'teks'], 
        'col2':['1', '2', '3', '4']}

df = pd.DataFrame(data)
df

   col1 col2
0     1    1
1     2    2
2     3    3
3  teks    4

In [3]:
df.dtypes

col1    object
col2    object
dtype: object

## Konversi tipe data dengan fungsi `astype()`

In [4]:
df_x = df.astype({'col2':'int'})
df_x

   col1  col2
0     1     1
1     2     2
2     3     3
3  teks     4

In [5]:
df_x.dtypes

col1    object
col2     int64
dtype: object

## Konversi tipe data numerik dengan fungsi `to_numeric()`

In [6]:
df.apply(pd.to_numeric, errors='coerce')

   col1  col2
0   1.0     1
1   2.0     2
2   3.0     3
3   NaN     4