# #15: Memecah nilai string dari suatu kolom ke dalam beberapa kolom baru
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
data = {'nama':['Didi Kempot', 'Glenn Fredly', 'Mbah Surip'], 
        'tempat_kelahiran':['Surakarta, Jawa Tengah', 'Jakarta, DKI Jakarta', 'Mojokerto, Jawa Timur']}
df = pd.DataFrame(data)
df

           nama        tempat_kelahiran
0   Didi Kempot  Surakarta, Jawa Tengah
1  Glenn Fredly    Jakarta, DKI Jakarta
2    Mbah Surip   Mojokerto, Jawa Timur

## Memecah nama depan dan nama belakang

In [3]:
df[['nama_depan', 'nama_belakang']] = df['nama'].str.split(' ', expand=True)
df

           nama        tempat_kelahiran nama_depan nama_belakang
0   Didi Kempot  Surakarta, Jawa Tengah       Didi        Kempot
1  Glenn Fredly    Jakarta, DKI Jakarta      Glenn        Fredly
2    Mbah Surip   Mojokerto, Jawa Timur       Mbah         Surip

## Memecah nama kota dan propinsi

In [4]:
df[['kota', 'propinsi']] = df['tempat_kelahiran'].str.split(',', expand=True)
df

,nama,tempat_kelahiran,nama_depan,nama_belakang,kota,propinsi
0,Didi Kempot,"Surakarta, Jawa Tengah",Didi,Kempot,Surakarta,Jawa Tengah
1,Glenn Fredly,"Jakarta, DKI Jakarta",Glenn,Fredly,Jakarta,DKI Jakarta
2,Mbah Surip,"Mojokerto, Jawa Timur",Mbah,Surip,Mojokerto,Jawa Timur