# #27: Mengenal fungsi agregasi `first()` dan `last()`
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
d = {'dokter':['Budi', 'Wati', 'Iwan', 'Budi', 'Budi', 'Wati'], 
     'pasien':['Abdul', 'Rahmat', 'Asep', 'Joko', 'Wiwin', 'Lisa']}

df = pd.DataFrame(d)
df

  dokter  pasien
0   Budi   Abdul
1   Wati  Rahmat
2   Iwan    Asep
3   Budi    Joko
4   Budi   Wiwin
5   Wati    Lisa

## Mengenal fungsi agregasi `first()` dan `last()`

In [3]:
df.groupby('dokter')['pasien'].count().to_frame()

        pasien
dokter
Budi         3
Iwan         1
Wati         2

In [4]:
df.groupby('dokter')['pasien'].first().to_frame()

        pasien
dokter
Budi     Abdul
Iwan      Asep
Wati    Rahmat

In [5]:
df.groupby('dokter')['pasien'].last().to_frame()

       pasien
dokter
Budi    Wiwin
Iwan     Asep
Wati     Lisa