# #33: Menampilkan nilai kumulatif (cummulative)
## Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.0.3

## Persiapan Data Frame

In [2]:
d = {'pemain':['Budi', 'Joni', 'Iwan', 'Budi', 'Budi', 'Iwan', 'Asep', 'Joni'], 
     'goal':[2, 1, 3, 1, 1, 2, 2, 3]}
df = pd.DataFrame(d)
df

  pemain  goal
0   Budi     2
1   Joni     1
2   Iwan     3
3   Budi     1
4   Budi     1
5   Iwan     2
6   Asep     2
7   Joni     3

## Menampilkan nilai kumulatif (cummulative)

In [3]:
df['goal'].cumsum().to_frame()

   goal
0     2
1     3
2     6
3     7
4     8
5    10
6    12
7    15

In [4]:
df['jumlah_goal_kumulatif'] = df['goal'].cumsum()
df

  pemain  goal  jumlah_goal_kumulatif
0   Budi     2                      2
1   Joni     1                      3
2   Iwan     3                      6
3   Budi     1                      7
4   Budi     1                      8
5   Iwan     2                     10
6   Asep     2                     12
7   Joni     3                     15

In [5]:
df['jumlah_goal_kumulatif_tiap_pemain'] = df.groupby('pemain')['goal'].cumsum()
df

  pemain  goal  jumlah_goal_kumulatif  jumlah_goal_kumulatif_tiap_pemain
0   Budi     2                      2                                  2
1   Joni     1                      3                                  1
2   Iwan     3                      6                                  3
3   Budi     1                      7                                  3
4   Budi     1                      8                                  4
5   Iwan     2                     10                                  5
6   Asep     2                     12                                  2
7   Joni     3                     15                                  4

In [6]:
df['cummax'] = df['goal'].cummax()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax
0,Budi,2,2,2,2
1,Joni,1,3,1,2
2,Iwan,3,6,3,3
3,Budi,1,7,3,3
4,Budi,1,8,4,3
5,Iwan,2,10,5,3
6,Asep,2,12,2,3
7,Joni,3,15,4,3

In [7]:
df['cummin'] = df['goal'].cummin()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax,cummin
0,Budi,2,2,2,2,2
1,Joni,1,3,1,2,1
2,Iwan,3,6,3,3,1
3,Budi,1,7,3,3,1
4,Budi,1,8,4,3,1
5,Iwan,2,10,5,3,1
6,Asep,2,12,2,3,1
7,Joni,3,15,4,3,1

In [8]:
df['cumprod'] = df['goal'].cumprod()
df

,pemain,goal,jumlah_goal_kumulatif,jumlah_goal_kumulatif_tiap_pemain,cummax,cummin,cumprod
0,Budi,2,2,2,2,2,2
1,Joni,1,3,1,2,1,2
2,Iwan,3,6,3,3,1,6
3,Budi,1,7,3,3,1,6
4,Budi,1,8,4,3,1,6
5,Iwan,2,10,5,3,1,12
6,Asep,2,12,2,3,1,24
7,Joni,3,15,4,3,1,72