# #05: Membalik urutan baris dan kolom pada Data Frame
## Import Modules

In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.0.3
1.24.3

## Persiapan Data Frame

In [2]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  1  3  6  1  8
1  4  3  3  3  6
2  5  4  6  7  7
3  8  4  6  7  6
4  3  7  8  4  1

## Membalik urutan kolom

In [3]:
df.loc[:, ::-1]

   E  D  C  B  A
0  8  1  6  3  1
1  6  3  3  3  4
2  7  7  6  4  5
3  6  7  6  4  8
4  1  4  8  7  3

## Membalik urutan baris

In [4]:
df.loc[::-1]

   A  B  C  D  E
4  3  7  8  4  1
3  8  4  6  7  6
2  5  4  6  7  7
1  4  3  3  3  6
0  1  3  6  1  8

## Membalik urutan baris dan melakukan penyesuaian ulang `index`

In [5]:
df.loc[::-1].reset_index(drop=True)

   A  B  C  D  E
0  3  7  8  4  1
1  8  4  6  7  6
2  5  4  6  7  7
3  4  3  3  3  6
4  1  3  6  1  8